version: '3.4'

services:

  # FRONTEND
  # ----
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: DEVELOPMENT
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      # Host: Container
      - "3000:3000"
      # - "443:443"

  backend:
    image: node:alpine
    #build:
    #  context: ./backend
    #  dockerfile: .containerfile